micronaut:
  application:
    name: micronaut-client-issues
  http:
    services:
      bad-client:
        urls:
          - http://localhost:8080/server2
      good-client:
        urls:
          - http://localhost:8080
  server:
    port: 8080
    cors:
      enabled: true